### ISSUE TITLE
[APIv2] GET /api/v2/messages panics on Error loading messages: EOF

### ISSUE THREAD

**Issue by stanislav-zaprudskiy** [mailhog/MailHog#314]
We are running MailHog in Kubernetes, using `mailhog/mailhog:v1.0.0` Docker image and have the storage engine configured for MongoDB. The same set-up is used for multiple different projects, but for all of them MailHog _periodically_ becomes unresponsive: HTTP returns 500, while SMTP refuses to store incoming messages. The corresponding log message:

```
[APIv2] GET /api/v2/messages
2020/08/06 16:00:19 Error loading messages: EOF
2020/08/06 16:00:19 http: panic serving 192.168.146.175:62364: EOF
goroutine 62967 [running]:
net/http.(*conn).serve.func1(0xc82007b100)
        /usr/lib/go/src/net/http/server.go:1389 +0xc1
panic(0x93f0a0, 0xc82000a0c0)
        /usr/lib/go/src/runtime/panic.go:443 +0x4e9
github.com/mailhog/MailHog-Server/api.(*APIv2).messages(0xc8201e4980, 0x7fcc930691d8, 0xc8200605b0, 0xc82011e2a0)
        /root/gocode/src/github.com/mailhog/MailHog-Server/api/v2.go:110 +0x22d
github.com/mailhog/MailHog-Server/api.(*APIv2).(github.com/mailhog/MailHog-Server/api.messages)-fm(0x7fcc930691d8, 0xc8200605b0, 0xc82011e2a0)
        /root/gocode/src/github.com/mailhog/MailHog-Server/api/v2.go:34 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc8201eae90, 0x7fcc930691d8, 0xc8200605b0, 0xc82011e2a0)
        /usr/lib/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/pat.(*Router).ServeHTTP(0xc820010af0, 0x7fcc930691d8, 0xc8200605b0, 0xc82011e2a0)
        /root/gocode/src/github.com/gorilla/pat/pat.go:92 +0x26e
github.com/mailhog/http.BasicAuthHandler.func1(0x7fcc930691d8, 0xc8200605b0, 0xc82011e2a0)
        /root/gocode/src/github.com/mailhog/http/server.go:92 +0xfd
net/http.HandlerFunc.ServeHTTP(0xc8201e57a0, 0x7fcc930691d8, 0xc8200605b0, 0xc82011e2a0)
        /usr/lib/go/src/net/http/server.go:1618 +0x3a
net/http.serverHandler.ServeHTTP(0xc8201fc680, 0x7fcc930691d8, 0xc8200605b0, 0xc82011e2a0)
        /usr/lib/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc82007b100)
        /usr/lib/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:2137 +0x44e
```

At the same time, MongoDB appears to be working fine. And what helps, is the restart of MailHog container - after which it becomes responsive and receives/returns messages until next occurrence of the problem.

What can we check additionally to understand the root cause?

**Comment by jay-dee7** [comment]
@stanislav-zaprudskiy the code base has a lot of unhandled errors plus `panic(err)` has been used at few places, i'm trying to work on few changes, share any updates whenever i have some

**Comment by Lajroni** [comment]
Still an issue with the latest Mailhog version in Kubernetes. After it works for some time, this error occurs and it doesn't get fixed until the container is restarted.

**Comment by Noname-OmerR** [comment]
@jay-dee7, any progress on this error? it's 2023 and we're still encountering it on latest docker version

**Comment by jay-dee7** [comment]
@OmerR95 I did build it but never raised a PR back. Plus it wan't anywhere close to production ready from what I remember. https://github.com/jay-dee7/MailHog-Server is my fork maybe it's worth looking at?

**Comment by jay-dee7** [comment]
TBH, I don't remember much of the work. I did start another project later on about multi-tenant mailhog backend. Maybe I should share that here
