### ISSUE TITLE
Logs file, and how to change it

### ISSUE THREAD

**Issue by Lumed7** [mailhog/MailHog#371]
Hi, 

I installed MailHog on a debian 10 vm with Golang.
I would like to create a directory specific to MailHog in /var/log (ex: /var/log/MailHog, and be able to make MailHog write its future logs in there.

Is it possible without docker ? How should I do it ?

Cheers

**Comment by StefGraf** [comment]
Can you just redirect the output to the log file?
MailHog_linux_amd64 > /var/log/mailhog.log 2>&1

**Comment by scottjacobsen** [comment]
I cannot release email either running version 1.0.1 - I see this in the log:
```
{Name:sendgrid Save:true Email:xxxx Host:smtp.sendgrid.com Port:25 Username:xxxx Password:xxxx Mechanism:PLAIN}
2022/01/04 14:33:16 http: panic serving 127.0.0.1:57533: runtime error: invalid memory address or nil pointer dereference
goroutine 34 [running]:
net/http.(*conn).serve.func1(0xc00030a000)
        /usr/local/Cellar/go/1.15.5/libexec/src/net/http/server.go:1801 +0x147
panic(0x1478bc0, 0x1873ad0)
        /usr/local/Cellar/go/1.15.5/libexec/src/runtime/panic.go:975 +0x47a
github.com/mailhog/MailHog/vendor/github.com/mailhog/MailHog-Server/api.(*APIv1).release_one(0xc000020500, 0x157d4a0, 0xc000328000, 0xc00030e100)
        /private/tmp/mailhog-20201127-95512-vdam6y/MailHog-1.0.1/src/github.com/mailhog/MailHog/vendor/github.com/mailhog/MailHog-Server/api/v1.go:277 +0x53f
net/http.HandlerFunc.ServeHTTP(0xc000020e30, 0x157d4a0, 0xc000328000, 0xc00030e100)
        /usr/local/Cellar/go/1.15.5/libexec/src/net/http/server.go:2042 +0x44
github.com/mailhog/MailHog/vendor/github.com/gorilla/pat.(*Router).ServeHTTP(0xc0000b6050, 0x157d4a0, 0xc000328000, 0xc00030e100)
        /private/tmp/mailhog-20201127-95512-vdam6y/MailHog-1.0.1/src/github.com/mailhog/MailHog/vendor/github.com/gorilla/pat/pat.go:92 +0x278
github.com/mailhog/MailHog/vendor/github.com/mailhog/http.BasicAuthHandler.func1(0x157d4a0, 0xc000328000, 0xc00030e100)
        /private/tmp/mailhog-20201127-95512-vdam6y/MailHog-1.0.1/src/github.com/mailhog/MailHog/vendor/github.com/mailhog/http/server.go:82 +0x207
net/http.HandlerFunc.ServeHTTP(0xc00000f7a0, 0x157d4a0, 0xc000328000, 0xc00030e100)
        /usr/local/Cellar/go/1.15.5/libexec/src/net/http/server.go:2042 +0x44
net/http.serverHandler.ServeHTTP(0xc0000fe0e0, 0x157d4a0, 0xc000328000, 0xc00030e100)
        /usr/local/Cellar/go/1.15.5/libexec/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc00030a000, 0x157e4a0, 0xc000312000)
        /usr/local/Cellar/go/1.15.5/libexec/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.15.5/libexec/src/net/http/server.go:2969 +0x36c
```
