### ISSUE TITLE
Enabling Jim crashes MailHog (Windows AMD64)

### ISSUE THREAD

**Issue by garethellis36** [mailhog/MailHog#66]
When I enable Jim, MailHog crashes on sending an email.

Environment:
- MailHog version v0.1.8 Windows AMD64
- Windows 7 Professional SP1 x64

Steps to reproduce:
- Enable Jim via web control panel
- Send email via MailHog SMTP

Console output:
```shell
c:\Program Files\Mailhog>MailHog_windows_amd64.exe
2015/11/04 11:38:34 Using in-memory storage
[HTTP] Binding to address: 0.0.0.0:8025
2015/11/04 11:38:34 [SMTP] Binding to address: 0.0.0.0:1025
Creating API v1
Creating API v2
[APIv1] GET /api/v1/events
[APIv2] GET /api/v2/jim
[APIv2] GET /api/v2/messages
[APIv1] GET /api/v1/events
[APIv2] POST /api/v2/jim
[APIv2] GET /api/v2/jim
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x5aba60]

goroutine 7 [running]:
github.com/mailhog/MailHog-Server/monkey.(*Jim).Accept(0xbc6b60, 0x393bf8, 0xc0820443d8, 0x0)
        /Users/ikent/dev/src/github.com/mailhog/MailHog-Server/monkey/jim.go:55 +0x70
github.com/mailhog/MailHog-Server/smtp.Listen(0xc0820b4750, 0xc08209a1e0, 0x0)
        /Users/ikent/dev/src/github.com/mailhog/MailHog-Server/smtp/smtp.go:27 +0x404
created by main.main
        /Users/ikent/dev/src/github.com/mailhog/MailHog/main.go:54 +0x151

goroutine 1 [chan receive]:
main.main()
        /Users/ikent/dev/src/github.com/mailhog/MailHog/main.go:58 +0x18d

goroutine 6 [IO wait]:
net.(*pollDesc).Wait(0xc0820b2bf0, 0x72, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc082044120, 0xc0820b2ae0, 0x9030b0, 0x8, 0xc0820f4040, 0xc08212a480, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/fd_windows.go:188 +0x305
net.(*netFD).acceptOne(0xc0820b2a80, 0xc0820aa0e0, 0x2, 0x2, 0xc0820b2ae0, 0x1000, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/fd_windows.go:558 +0x547
net.(*netFD).accept(0xc0820b2a80, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/fd_windows.go:585 +0x17a
net.(*TCPListener).AcceptTCP(0xc0820441c8, 0x463c65, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/tcpsock_posix.go:234 +0x55
net/http.tcpKeepAliveListener.Accept(0xc0820441c8, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1976 +0x53
net/http.(*Server).Serve(0xc08209b140, 0x393bc0, 0xc0820441c8, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1728 +0x99
net/http.(*Server).ListenAndServe(0xc08209b140, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1718 +0x15b
net/http.ListenAndServe(0x902a30, 0xc, 0x392888, 0xc08200da40, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1808 +0xc1
github.com/mailhog/http.Listen(0x902a30, 0xc, 0x9e1f70, 0xc08209a1e0, 0x9e28e8)
        /Users/ikent/dev/src/github.com/mailhog/http/server.go:17 +0x227
created by main.main
        /Users/ikent/dev/src/github.com/mailhog/MailHog/main.go:42 +0x129

goroutine 10 [chan receive]:
github.com/mailhog/MailHog-Server/api.func┬╖001()
        /Users/ikent/dev/src/github.com/mailhog/MailHog-Server/api/v1.go:66 +0x7a
created by github.com/mailhog/MailHog-Server/api.CreateAPIv1
        /Users/ikent/dev/src/github.com/mailhog/MailHog-Server/api/v1.go:74 +0x1253

goroutine 12 [IO wait]:
net.(*pollDesc).Wait(0xc0820b2ef0, 0x72, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc082044120, 0xc0820b2de0, 0x8e7c20, 0x7, 0x9e29d8, 0x6ec1, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/fd_windows.go:188 +0x305
net.(*netFD).Read(0xc0820b2d80, 0xc08209f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/fd_windows.go:470 +0x180
net.(*conn).Read(0xc082044280, 0xc08209f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/net.go:121 +0xe3
net/http.(*liveSwitchReader).Read(0xc08205bc68, 0xc08209f000, 0x1000, 0x1000, 0x4127c9, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:214 +0xb2
io.(*LimitedReader).Read(0xc0820cf7c0, 0xc08209f000, 0x1000, 0x1000, 0xbc7820, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/io/io.go:408 +0xd5
bufio.(*Reader).fill(0xc08209b200)
        /usr/local/Cellar/go/1.4/libexec/src/bufio/bufio.go:97 +0x1d5
bufio.(*Reader).ReadSlice(0xc08209b200, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/bufio/bufio.go:295 +0x25e
bufio.(*Reader).ReadLine(0xc08209b200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/bufio/bufio.go:324 +0x69
net/textproto.(*Reader).readLineSlice(0xc082291260, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/textproto/reader.go:55 +0xa5
net/textproto.(*Reader).ReadLine(0xc082291260, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/textproto/reader.go:36 +0x56
net/http.ReadRequest(0xc08209b200, 0xc0822ae410, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/http/request.go:598 +0xd2
net/http.(*conn).readRequest(0xc08205bc20, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:586 +0x276
net/http.(*conn).serve(0xc08205bc20)
        /usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1162 +0x6a5
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1751 +0x365

goroutine 13 [IO wait]:
net.(*pollDesc).Wait(0xc0820b3070, 0x72, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc082044120, 0xc0820b2f60, 0x8e7c20, 0x7, 0x9e29d8, 0xb2714e, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/fd_windows.go:188 +0x305
net.(*netFD).Read(0xc0820b2f00, 0xc082067000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/fd_windows.go:470 +0x180
net.(*conn).Read(0xc082044288, 0xc082067000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/net.go:121 +0xe3
net/http.(*liveSwitchReader).Read(0xc08205bd08, 0xc082067000, 0x1000, 0x1000, 0x4127c9, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:214 +0xb2
io.(*LimitedReader).Read(0xc0820cf800, 0xc082067000, 0x1000, 0x1000, 0xbc7820, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/io/io.go:408 +0xd5
bufio.(*Reader).fill(0xc08209b260)
        /usr/local/Cellar/go/1.4/libexec/src/bufio/bufio.go:97 +0x1d5
bufio.(*Reader).ReadSlice(0xc08209b260, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/bufio/bufio.go:295 +0x25e
bufio.(*Reader).ReadLine(0xc08209b260, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/bufio/bufio.go:324 +0x69
net/textproto.(*Reader).readLineSlice(0xc0822913b0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/textproto/reader.go:55 +0xa5
net/textproto.(*Reader).ReadLine(0xc0822913b0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/textproto/reader.go:36 +0x56
net/http.ReadRequest(0xc08209b260, 0xc0822ae680, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/http/request.go:598 +0xd2
net/http.(*conn).readRequest(0xc08205bcc0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:586 +0x276
net/http.(*conn).serve(0xc08205bcc0)
        /usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1162 +0x6a5
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1751 +0x365

goroutine 15 [IO wait]:
net.(*pollDesc).Wait(0xc0820b3370, 0x72, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc082044120, 0xc0820b3260, 0x8e7c20, 0x7, 0x9e29d8, 0xb2714e, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/fd_windows.go:188 +0x305
net.(*netFD).Read(0xc0820b3200, 0xc082103000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/fd_windows.go:470 +0x180
net.(*conn).Read(0xc082044298, 0xc082103000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/net.go:121 +0xe3
net/http.(*liveSwitchReader).Read(0xc08204e048, 0xc082103000, 0x1000, 0x1000, 0x4127c9, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:214 +0xb2
io.(*LimitedReader).Read(0xc0820cfa80, 0xc082103000, 0x1000, 0x1000, 0xbc7820, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/io/io.go:408 +0xd5
bufio.(*Reader).fill(0xc08209b3e0)
        /usr/local/Cellar/go/1.4/libexec/src/bufio/bufio.go:97 +0x1d5
bufio.(*Reader).ReadSlice(0xc08209b3e0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/bufio/bufio.go:295 +0x25e
bufio.(*Reader).ReadLine(0xc08209b3e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/bufio/bufio.go:324 +0x69
net/textproto.(*Reader).readLineSlice(0xc0822900c0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/textproto/reader.go:55 +0xa5
net/textproto.(*Reader).ReadLine(0xc0822900c0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/textproto/reader.go:36 +0x56
net/http.ReadRequest(0xc08209b3e0, 0xc0822af1e0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/http/request.go:598 +0xd2
net/http.(*conn).readRequest(0xc08204e000, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:586 +0x276
net/http.(*conn).serve(0xc08204e000)
        /usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1162 +0x6a5
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1751 +0x365

goroutine 16 [IO wait]:
net.(*pollDesc).Wait(0xc08212a170, 0x72, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc082044120, 0xc08212a060, 0x8e7c20, 0x7, 0x9e29d8, 0x2bbf, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/fd_windows.go:188 +0x305
net.(*netFD).Read(0xc08212a000, 0xc082139000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/fd_windows.go:470 +0x180
net.(*conn).Read(0xc082044030, 0xc082139000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/net.go:121 +0xe3
net/http.(*liveSwitchReader).Read(0xc08205a228, 0xc082139000, 0x1000, 0x1000, 0x4127c9, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:214 +0xb2
io.(*LimitedReader).Read(0xc0820ce140, 0xc082139000, 0x1000, 0x1000, 0xbc7820, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/io/io.go:408 +0xd5
bufio.(*Reader).fill(0xc08209a000)
        /usr/local/Cellar/go/1.4/libexec/src/bufio/bufio.go:97 +0x1d5
bufio.(*Reader).ReadSlice(0xc08209a000, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/bufio/bufio.go:295 +0x25e
bufio.(*Reader).ReadLine(0xc08209a000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/bufio/bufio.go:324 +0x69
net/textproto.(*Reader).readLineSlice(0xc082291350, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/textproto/reader.go:55 +0xa5
net/textproto.(*Reader).ReadLine(0xc082291350, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/textproto/reader.go:36 +0x56
net/http.ReadRequest(0xc08209a000, 0xc0822ae4e0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/http/request.go:598 +0xd2
net/http.(*conn).readRequest(0xc08205a1e0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:586 +0x276
net/http.(*conn).serve(0xc08205a1e0)
        /usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1162 +0x6a5
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1751 +0x365

goroutine 17 [IO wait]:
net.(*pollDesc).Wait(0xc08212a2f0, 0x72, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc082044120, 0xc08212a1e0, 0x8e7c20, 0x7, 0x9e29d8, 0x36d26, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/fd_windows.go:188 +0x305
net.(*netFD).Read(0xc08212a180, 0xc082105000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/fd_windows.go:470 +0x180
net.(*conn).Read(0xc082044018, 0xc082105000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/net.go:121 +0xe3
net/http.(*liveSwitchReader).Read(0xc08205a5e8, 0xc082105000, 0x1000, 0x1000, 0xc082140140, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:214 +0xb2
io.(*LimitedReader).Read(0xc08213e000, 0xc082105000, 0x1000, 0x1000, 0xbc7820, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/io/io.go:408 +0xd5
bufio.(*Reader).fill(0xc08209a120)
        /usr/local/Cellar/go/1.4/libexec/src/bufio/bufio.go:97 +0x1d5
bufio.(*Reader).ReadSlice(0xc08209a120, 0x39340a, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/bufio/bufio.go:295 +0x25e
bufio.(*Reader).ReadLine(0xc08209a120, 0x0, 0x0, 0x0, 0xc081fd6e00, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/bufio/bufio.go:324 +0x69
net/textproto.(*Reader).readLineSlice(0xc082291380, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/textproto/reader.go:55 +0xa5
net/textproto.(*Reader).ReadLine(0xc082291380, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/textproto/reader.go:36 +0x56
net/http.ReadRequest(0xc08209a120, 0xc0822ae0d0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/http/request.go:598 +0xd2
net/http.(*conn).readRequest(0xc08205a5a0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:586 +0x276
net/http.(*conn).serve(0xc08205a5a0)
        /usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1162 +0x6a5
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1751 +0x365

c:\Program Files\Mailhog>

c:\Program Files\Mailhog>dir
 Volume in drive C has no label.
 Volume Serial Number is 267F-AD61

 Directory of c:\Program Files\Mailhog

31/07/2015  09:46    <DIR>          .
31/07/2015  09:46    <DIR>          ..
31/07/2015  09:46            99,678 hog.ico
24/07/2015  14:09        11,354,624 MailHog_windows_amd64.exe
               2 File(s)     11,454,302 bytes
               2 Dir(s)  172,274,348,032 bytes free

c:\Program Files\Mailhog>MailHog_windows_amd64.exe
2015/11/04 11:42:48 Using in-memory storage
2015/11/04 11:42:48 [SMTP] Binding to address: 0.0.0.0:1025
2015/11/04 11:42:48 [SMTP] Error listening on socket: listen tcp 0.0.0.0:1025: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

c:\Program Files\Mailhog>MailHog_windows_amd64.exe
2015/11/04 11:43:04 Using in-memory storage
2015/11/04 11:43:04 [SMTP] Binding to address: 0.0.0.0:1025
[HTTP] Binding to address: 0.0.0.0:8025
Creating API v1
Creating API v2
[APIv1] GET /api/v1/events
[APIv2] GET /api/v2/jim
[APIv2] GET /api/v2/messages
[APIv1] GET /api/v1/events
[APIv2] POST /api/v2/jim
[APIv2] GET /api/v2/jim
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x60bd91]

goroutine 6 [running]:
github.com/mailhog/MailHog-Server/monkey.(*Jim).Accept(0xbd24c0, 0x1204000, 0xc0825ae218, 0x0)
        /Users/ikent/dev/src/github.com/mailhog/MailHog-Server/monkey/jim.go:55 +0x61
github.com/mailhog/MailHog-Server/smtp.Listen(0xc082033520, 0xc0820d5740, 0x0)
        /Users/ikent/dev/src/github.com/mailhog/MailHog-Server/smtp/smtp.go:27 +0x42b
created by main.main
        /Users/ikent/dev/src/github.com/mailhog/MailHog/main.go:91 +0x8a2

goroutine 1 [chan receive]:
main.main()
        /Users/ikent/dev/src/github.com/mailhog/MailHog/main.go:95 +0x8dc

goroutine 5 [IO wait]:
net.runtime_pollWait(0x3c5808, 0x72, 0xc0821afbd0)
        /usr/local/Cellar/go/1.5/libexec/src/runtime/netpoll.go:157 +0x67
net.(*pollDesc).Wait(0xc082111070, 0x72, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/net/fd_poll_runtime.go:73 +0x41
net.(*ioSrv).ExecIO(0xc082024048, 0xc082110f60, 0x909260, 0x8, 0xc0821a8780, 0xc0821b8600, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/net/fd_windows.go:182 +0x177
net.(*netFD).acceptOne(0xc082110f00, 0xc0821c2460, 0x2, 0x2, 0xc082110f60, 0x899500, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/net/fd_windows.go:564 +0x26c
net.(*netFD).accept(0xc082110f00, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/net/fd_windows.go:594 +0x173
net.(*TCPListener).AcceptTCP(0xc0820fc220, 0x450640, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/net/tcpsock_posix.go:254 +0x54
net/http.tcpKeepAliveListener.Accept(0xc0820fc220, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/net/http/server.go:2135 +0x48
net/http.(*Server).Serve(0xc0820f5d40, 0x11a0590, 0xc0820fc220, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/net/http/server.go:1887 +0xba
net/http.(*Server).ListenAndServe(0xc0820f5d40, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/net/http/server.go:1877 +0x13d
net/http.ListenAndServe(0x908f30, 0xc, 0x11a01f0, 0xc0821853a0, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/net/http/server.go:1967 +0x96
github.com/mailhog/http.Listen(0x908f30, 0xc, 0x9d3cf0, 0xc0820d5740, 0x9d4008)
        /Users/ikent/dev/src/github.com/mailhog/http/server.go:108 +0x25b
created by main.main
        /Users/ikent/dev/src/github.com/mailhog/MailHog/main.go:79 +0x872

goroutine 8 [IO wait]:
net.runtime_pollWait(0x3c5508, 0x72, 0xc082497470)
        /usr/local/Cellar/go/1.5/libexec/src/runtime/netpoll.go:157 +0x67
net.(*pollDesc).Wait(0xc08201b370, 0x72, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/net/fd_poll_runtime.go:73 +0x41
net.(*ioSrv).ExecIO(0xc082024048, 0xc08201b260, 0x900960, 0x7, 0x9d4068, 0x2, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/net/fd_windows.go:182 +0x177
net.(*netFD).Read(0xc08201b200, 0xc08221b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/net/fd_windows.go:463 +0x17e
net.(*conn).Read(0xc082024068, 0xc08221b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.5/libexec/src/net/net.go:172 +0xeb
```

**Comment by dariuskt** [comment]
exact same issue with* v0.1.8/MailHog_linux_amd64

```
$ uname -a
Linux 7cda3e1c3a9b 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux
$ dpkg -l | grep go
ii  golang                     2:1.3.3-1                 all          Go programming language compiler - metapackage
ii  golang-doc                 2:1.3.3-1                 all          Go programming language compiler - documentation
ii  golang-go                  2:1.3.3-1                 amd64        Go programming language compiler
ii  golang-go-linux-amd64      2:1.3.3-1                 amd64        Go standard library compiled for linux_amd64
ii  golang-src                 2:1.3.3-1                 amd64        Go programming language compiler - source files
```

adding a cli option to hide jim from web interface could be quick solution.

**Comment by dariuskt** [comment]
issue is 100% reproducible with 
* older releases (0.1.3~0.1.8); golang 1.3 as above (didn't tested older releases)
* 0.1.8 and golang 1.4
* docker container

are there some dependencies or setup i'm missing?
